/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlybaidoxe.quanlydoxe;

import javax.swing.JFrame;


import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import com.mycompany.quanlybaidoxe.maxacnhan.xacnhanQr;
import com.mycompany.quanlybaidoxe.maxacnhan.xacnhanma;
import com.mycompany.quanlybaidoxe.timkiembai.Luachonbai;
import com.mycompany.quanlybaidoxe.timkiembai.Timkiemtudong;
import com.mycompany.quanlybaidoxe.trabai.Trabai;
import com.mycompany.quanlybaidoxe.quanlydoxe.loitaothongtin;
import com.mycompany.quanlybaidoxe.quanlydoxe.baoloi;
import com.mycompany.quanlybaidoxe.quanlydoxe.User;
import com.mycompany.quanlybaidoxe.LogIn.LogIn;

/**
 *
 * @author nhannt
 */
public class Giaodienchinh extends javax.swing.JFrame {
    
    
    
    //nhập loại xe và biển số
    private String nt="";//loại xe
    private String nb="";//biển số
    
    //dữ liệu tài khoản 
    private String tnd="";
    private String bsx="";
    private String tkdn="";
    private int sl=0;
    
    //
    
    
    /**
     * Creates new form Giaodienchinh
     */
    public Giaodienchinh() {

        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        customizeTextField();
        setLocationRelativeTo(null);
        setResizable(false);
        
        JPmc.add(JPttb, "JPttb");
        JPmc.add(JPtrb,"JPtrb");
        JPmc.add(JPvb,"JPvb");
        JPmc.add(JPtkb,"JPtkb");
        JPmc.add(JPtk,"JPtk");      
        
        CardLayout cl = (CardLayout) JPmc.getLayout();
        cl.show(JPmc, "empty"); 
        
    }
    private void customizeTextField() {
        // Thêm placeholder cho JTnt (TextField biển số xe)
        
        JTbxwir.setText("Nhập biển số xe...vd:30V-123.12");
        JTbxwir.setForeground(Color.GRAY);


         JTbxwir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (JTbxwir.getText().equals("Nhập biển số xe...vd:30V-123.12")) {
                    JTbxwir.setText("");
                    JTbxwir.setForeground(Color.BLACK); // Đổi màu chữ khi người dùng nhập
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (JTbxwir.getText().isEmpty()) {
                    JTbxwir.setText("Nhập biển số xe...vd:30V-123.12");
                    JTbxwir.setForeground(Color.GRAY); // Trả lại màu placeholder nếu không có nội dung
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel thanhcongcu = new BackgroundPanel("/quanlydoxe_img/n1.png");
        Bthongtinxe = new javax.swing.JButton();
        Btimkiem = new javax.swing.JButton();
        Btra = new javax.swing.JButton();
        Bxacnhan = new javax.swing.JButton();
        Bthoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JPmc = new BackgroundPanel("/quanlydoxe_img/Wellcom.png");
        javax.swing.JPanel jPanel2 = new BackgroundPanel("/quanlydoxe_img/Wellcom.png");
        JPtrb = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JPttb = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTbxwir = new javax.swing.JTextField();
        JBxntt = new javax.swing.JButton();
        JClx = new javax.swing.JComboBox<>();
        JPvb = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JBqrv = new javax.swing.JButton();
        JBmv = new javax.swing.JButton();
        JPtkb = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        JPtk = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLtnd = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JLbsx = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JLtkdn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        JLsltb = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Packing");
        setBackground(new java.awt.Color(255, 255, 255));

        Bthongtinxe.setBackground(new java.awt.Color(0, 90, 199));
        Bthongtinxe.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Bthongtinxe.setForeground(new java.awt.Color(0, 0, 0));
        Bthongtinxe.setText("Tạo thông tin xe");
        Bthongtinxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthongtinxeActionPerformed(evt);
            }
        });

        Btimkiem.setBackground(new java.awt.Color(0, 90, 199));
        Btimkiem.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Btimkiem.setForeground(new java.awt.Color(0, 0, 0));
        Btimkiem.setText("Tìm kiếm chỗ đỗ xe");
        Btimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtimkiemActionPerformed(evt);
            }
        });

        Btra.setBackground(new java.awt.Color(0, 90, 199));
        Btra.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Btra.setForeground(new java.awt.Color(0, 0, 0));
        Btra.setText("Trả bãi đỗ xe");
        Btra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtraActionPerformed(evt);
            }
        });

        Bxacnhan.setBackground(new java.awt.Color(0, 90, 199));
        Bxacnhan.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Bxacnhan.setForeground(new java.awt.Color(0, 0, 0));
        Bxacnhan.setText("QR xác nhận vào bãi");
        Bxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxacnhanActionPerformed(evt);
            }
        });

        Bthoat.setBackground(new java.awt.Color(0, 90, 199));
        Bthoat.setForeground(new java.awt.Color(0, 0, 0));
        Bthoat.setText("Exit");
        Bthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthoatActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlydoxe_img/2.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlydoxe_img/3.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlydoxe_img/1.png"))); // NOI18N
        jLabel3.setText("CHỨC NĂNG");

        jButton2.setBackground(new java.awt.Color(0, 90, 199));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Tài khoản");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thanhcongcuLayout = new javax.swing.GroupLayout(thanhcongcu);
        thanhcongcu.setLayout(thanhcongcuLayout);
        thanhcongcuLayout.setHorizontalGroup(
            thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanhcongcuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bthoat, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(thanhcongcuLayout.createSequentialGroup()
                .addGroup(thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bthongtinxe, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btra, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thanhcongcuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thanhcongcuLayout.setVerticalGroup(
            thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanhcongcuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(Bthongtinxe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btra, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(thanhcongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        JPmc.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        JPmc.add(jPanel2, "card3");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel7.setText("Trả bãi đỗ xe");

        jButton1.setBackground(new java.awt.Color(0, 90, 199));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Xác nhận trả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPtrbLayout = new javax.swing.GroupLayout(JPtrb);
        JPtrb.setLayout(JPtrbLayout);
        JPtrbLayout.setHorizontalGroup(
            JPtrbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtrbLayout.createSequentialGroup()
                .addGroup(JPtrbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPtrbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(JPtrbLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        JPtrbLayout.setVerticalGroup(
            JPtrbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtrbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(169, 169, 169)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        JPmc.add(JPtrb, "card4");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel4.setText("Tạo thông tin xe");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("Nhập biển số xe");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Chọn loại xe");

        JTbxwir.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JTbxwir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbxwirActionPerformed(evt);
            }
        });

        JBxntt.setBackground(new java.awt.Color(0, 90, 199));
        JBxntt.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        JBxntt.setForeground(new java.awt.Color(0, 0, 0));
        JBxntt.setText("Xác nhận");
        JBxntt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBxnttActionPerformed(evt);
            }
        });

        JClx.setBackground(new java.awt.Color(255, 255, 255));
        JClx.setForeground(new java.awt.Color(255, 255, 255));
        JClx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe thô sơ", "Xe cơ giới (xe gắn máy)", "Xe cơ giới(xe ô tô)", "Xe chuyên dụng" }));
        JClx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPttbLayout = new javax.swing.GroupLayout(JPttb);
        JPttb.setLayout(JPttbLayout);
        JPttbLayout.setHorizontalGroup(
            JPttbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPttbLayout.createSequentialGroup()
                .addGroup(JPttbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPttbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(JPttbLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(JPttbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(JTbxwir, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(JClx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JPttbLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(JBxntt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        JPttbLayout.setVerticalGroup(
            JPttbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPttbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTbxwir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JClx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBxntt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        JPmc.add(JPttb, "card2");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel8.setText("Xác nhận vào bãi");

        JBqrv.setBackground(new java.awt.Color(0, 90, 199));
        JBqrv.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        JBqrv.setForeground(new java.awt.Color(0, 0, 0));
        JBqrv.setText("QR xác nhận");
        JBqrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBqrvActionPerformed(evt);
            }
        });

        JBmv.setBackground(new java.awt.Color(0, 90, 199));
        JBmv.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        JBmv.setForeground(new java.awt.Color(0, 0, 0));
        JBmv.setText("Mã xác nhận");
        JBmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPvbLayout = new javax.swing.GroupLayout(JPvb);
        JPvb.setLayout(JPvbLayout);
        JPvbLayout.setHorizontalGroup(
            JPvbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvbLayout.createSequentialGroup()
                .addGroup(JPvbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPvbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(JPvbLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(JPvbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBqrv, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(JBmv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        JPvbLayout.setVerticalGroup(
            JPvbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(99, 99, 99)
                .addComponent(JBqrv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(JBmv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        JPmc.add(JPvb, "card5");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel9.setText("Tìm kiếm bãi đỗ xe");

        jButton4.setBackground(new java.awt.Color(0, 90, 199));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Tìm kiếm tự động");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 90, 199));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Lựa chọn bãi đỗ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPtkbLayout = new javax.swing.GroupLayout(JPtkb);
        JPtkb.setLayout(JPtkbLayout);
        JPtkbLayout.setHorizontalGroup(
            JPtkbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtkbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPtkbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel9))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        JPtkbLayout.setVerticalGroup(
            JPtkbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtkbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(78, 78, 78)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        JPmc.add(JPtkb, "card6");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel10.setText("Thông tin người dùng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JLtnd.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JLtnd.setForeground(new java.awt.Color(0, 0, 0));
        JLtnd.setText("Chưa có thông tin ...");
        JLtnd.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLtndAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtnd, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        JLbsx.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JLbsx.setForeground(new java.awt.Color(0, 0, 0));
        JLbsx.setText("Chưa có thông tin ...");
        JLbsx.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLbsxAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLbsx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLbsx, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        JLtkdn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JLtkdn.setForeground(new java.awt.Color(0, 0, 0));
        JLtkdn.setText("Chưa có thông tin...");
        JLtkdn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLtkdnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtkdn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtkdn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        JLsltb.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JLsltb.setForeground(new java.awt.Color(0, 0, 0));
        JLsltb.setText("Chưa có thông tin...");
        JLsltb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLsltbAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLsltb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLsltb, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel15.setText("Tên người dùng");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel16.setText("Biển số xe");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel17.setText("Tài khoản đăng nhập");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel18.setText("Số lần thuê bãi");

        javax.swing.GroupLayout JPtkLayout = new javax.swing.GroupLayout(JPtk);
        JPtk.setLayout(JPtkLayout);
        JPtkLayout.setHorizontalGroup(
            JPtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtkLayout.createSequentialGroup()
                .addGroup(JPtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPtkLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(JPtkLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(JPtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPtkLayout.createSequentialGroup()
                                .addGroup(JPtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGap(0, 187, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPtkLayout.setVerticalGroup(
            JPtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        JPmc.add(JPtk, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(thanhcongcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JPmc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thanhcongcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPmc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BthongtinxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthongtinxeActionPerformed
        // TODO add your handling code here:
        User user = User.getInstance();
        System.out.println(user.getBienSo()+" " + user.getGio()+ " " + user.getName()+ " " + user.getPhut()+" " +user.getSpotId()+" " +user.getUsername() +" "+ user.getQrCode() +" "+user.getTrangThaiXe());
        
        CardLayout cl = (CardLayout) JPmc.getLayout();
        cl.show(JPmc, "JPttb");
    }//GEN-LAST:event_BthongtinxeActionPerformed

    private void BtimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtimkiemActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) JPmc.getLayout();
        cl.show(JPmc, "JPtkb");
    }//GEN-LAST:event_BtimkiemActionPerformed

    private void BtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtraActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) JPmc.getLayout();
        cl.show(JPmc, "JPtrb");
        
    }//GEN-LAST:event_BtraActionPerformed

    private void BxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxacnhanActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) JPmc.getLayout();
        cl.show(JPmc, "JPvb");
    }//GEN-LAST:event_BxacnhanActionPerformed

    private void BthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthoatActionPerformed
        // TODO add your handling code here:
        
        
        new LogIn().setVisible(true);
        this.dispose();
        // trả lại trang đăng nhập
        
    }//GEN-LAST:event_BthoatActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //hiện frame tìm kiếm tự động và xác nhận hoặc tìm kiếm tự động tiếp hoặc quay lại
        new Timkiemtudong().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JBxnttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBxnttActionPerformed
        // TODO add your handling code here:
        loitaothongtin k = new loitaothongtin();

        nt = String.valueOf(JClx.getSelectedIndex());
        nb = JTbxwir.getText();
        
        int h1 = k.kiem(nb, nt);

        if (h1 == -4) {
            baoloi baoloi = new baoloi(Giaodienchinh.this, true);
            baoloi.showPanel("card2");
            nt = "";
            baoloi.setVisible(true);
        } else if (h1 == -3) {
            baoloi baoloi = new baoloi(Giaodienchinh.this, true);
            baoloi.showPanel("card3");
            nt = "";
            baoloi.setVisible(true);
        } else if (h1 == -2) {
            baoloi baoloi = new baoloi(Giaodienchinh.this, true);
            baoloi.showPanel("card4");
            nt = "";
            baoloi.setVisible(true);
        } else if (h1 == -1) {
            baoloi baoloi = new baoloi(Giaodienchinh.this, true);
            baoloi.showPanel("card5");
            nt = "";
            baoloi.setVisible(true);
        } else if (h1 == 1) {
            bsx = nb; // Lưu lại nb vào bsx trước khi reset
            String filePath = "data_Customer.xml"; 
            UserUpdater userUpdater = new UserUpdater(filePath);
            User user = User.getInstance();
            user.setBienSo(bsx);
            userUpdater.updateUser(user);

            
            baoloi baoloi = new baoloi(Giaodienchinh.this, true);
            baoloi.showPanel("card6");
            baoloi.setVisible(true);
            System.out.println(user.getBienSo()+" " + user.getGio()+ " " + user.getName()+ " " + user.getPhut()+" " +user.getSpotId()+" " +user.getUsername() +" "+ user.getQrCode() +" "+user.getTrangThaiXe());
        }
        //lưu vào data để chỉ có một cái biển số xe thôi
  
    }//GEN-LAST:event_JBxnttActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //hiện frame lựa chọn các chỗ còn trống
        new Luachonbai().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // chuyển đến frame tính tiền xuất  hoá đơn và kèm mã qr trả tiền.
        new Trabai().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBqrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBqrvActionPerformed
        // TODO add your handling code here:
        //chuyển đến frame  hiện qr 
        new xacnhanQr().setVisible(true);
        
        
    }//GEN-LAST:event_JBqrvActionPerformed

    private void JBmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmvActionPerformed
        // TODO add your handling code here:
        //chuyển đến frame  hiện mã tự tạo và tạo khung nhập.
        //nếu nhập đúng sẽ tạo mã lưu xe đã vào là biển số.
        new xacnhanma().setVisible(true);
        //đã nhập đúng
        
    }//GEN-LAST:event_JBmvActionPerformed

    private void JLtndAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLtndAncestorAdded
        // TODO add your handling code here:
        User user = User.getInstance();
        tnd = user.getName();
        if(tnd.length() == 0){
            JLtnd.setText("Chưa có thông tin...");
        }else{
            JLtnd.setText(tnd);
        }
        
    }//GEN-LAST:event_JLtndAncestorAdded

    private void JLbsxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLbsxAncestorAdded
        // TODO add your handling code here:
        if(bsx.length() == 0){
            JLbsx.setText("Chưa có thông tin...");
        }else{
            JLbsx.setText(bsx);
        }
    }//GEN-LAST:event_JLbsxAncestorAdded

    private void JLtkdnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLtkdnAncestorAdded
        // TODO add your handling code here:
        User user = User.getInstance();
        tkdn = user.getUsername();
        if(tkdn.length() == 0){
            JLtkdn.setText("Chưa có thông tin...");
        }else{
            JLtkdn.setText(tkdn);
        }
    }//GEN-LAST:event_JLtkdnAncestorAdded

    private void JLsltbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLsltbAncestorAdded
        // TODO add your handling code here:
        JLsltb.setText(String.valueOf(sl));
    }//GEN-LAST:event_JLsltbAncestorAdded

    private void JClxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JClxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) JPmc.getLayout();
        cl.show(JPmc, "JPtk");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTbxwirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbxwirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JTbxwirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Giaodienchinh().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bthoat;
    private javax.swing.JButton Bthongtinxe;
    private javax.swing.JButton Btimkiem;
    private javax.swing.JButton Btra;
    private javax.swing.JButton Bxacnhan;
    private javax.swing.JButton JBmv;
    private javax.swing.JButton JBqrv;
    private javax.swing.JButton JBxntt;
    private javax.swing.JComboBox<String> JClx;
    private javax.swing.JLabel JLbsx;
    private javax.swing.JLabel JLsltb;
    private javax.swing.JLabel JLtkdn;
    private javax.swing.JLabel JLtnd;
    private javax.swing.JPanel JPmc;
    private javax.swing.JPanel JPtk;
    private javax.swing.JPanel JPtkb;
    private javax.swing.JPanel JPtrb;
    private javax.swing.JPanel JPttb;
    private javax.swing.JPanel JPvb;
    private javax.swing.JTextField JTbxwir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
